@apiUrl = http://localhost:3070/boards

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTI3ZGEyY2YyOTEzNzkxODY4YjAzYjUiLCJuYW1lIjoiVG9waTEiLCJ1c2VyIjoiVG9waTEiLCJleHBpcmVzSW4iOiIxZCIsImlhdCI6MTY5NzExMDU3Nn0.ucpfIve5jxOBJyx-jQ4nMkuHn8L6Sb14vcbXP6amt7c




### GET ALL BOARDS FOR AUTHENTICATED USER
GET {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

### CREATE NEW BOARD
POST {{apiUrl}}/kaki
Authorization: Bearer {{token}}

### UPDATE BOARD epicboard
PATCH {{apiUrl}}/6527da42f2913791868b03b6
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "boardUsers": ["Erik", "Tobias", "Erik4"]
}


### DELETE BOARD
DELETE {{apiUrl}}/6527aa2517ad8e8e91dd416a
Authorization: Bearer {{token}}
