@apiUrl = http://localhost:3070/boards

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTI1OTQ0NzhjYzFlNDc1OTBmYTVhYmEiLCJuYW1lIjoiVG9waSIsImV4cGlyZXNJbiI6IjFkIiwiaWF0IjoxNjk2OTYzNTg0fQ.uhKYk8Mk3M-aKxMAfWcwJ40FYiGV_hitKCrCWkB6drg


### GET ALL BOARDS FOR AUTHENTICATED USER
GET {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

### CREATE NEW BOARD
POST {{apiUrl}}/epicboard
Authorization: Bearer {{token}}

### UPDATE BOARD epicboard
PUT {{apiUrl}}/652581f7e68cbc591e65de30
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "boardUsers": ["Erik", "tobias"],
    "notes": "12341541234"
}


### DELETE BOARD
DELETE {{apiUrl}}/652579bd67a5a40af3539acd
Authorization: Bearer {{token}}
