@apiUrl = http://localhost:3070/boards

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTI4MjVlOGM1YjNlODJjMTBkYjA0YmEiLCJuYW1lIjoiRXJpayIsInVzZXIiOiJFcmlrIiwiZXhwaXJlc0luIjoiMWQiLCJpYXQiOjE2OTcxMzAyNTl9.iPvYUbaxQOkctmNgNR21qsleJHpxa8j_z7LZx_rM5J4




### GET ALL BOARDS FOR AUTHENTICATED USER
GET {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

### CREATE NEW BOARD
POST {{apiUrl}}/kakibaki
Authorization: Bearer {{token}}

### UPDATE BOARD epicboard
PATCH {{apiUrl}}/65280c59b3b563a79bc02040
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "boardUsers": ["Topi"]
}


### DELETE BOARD
DELETE {{apiUrl}}/6527aa2517ad8e8e91dd416a
Authorization: Bearer {{token}}
