@apiUrl = http://localhost:3070/login

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTE5NmU2MWRjZmEzNThhNjkwMTFiNzUiLCJuYW1lIjoiRXJpayIsImV4cGlyZXNJbiI6IjFkIiwiaWF0IjoxNjk2OTUyODE0fQ.J81Nt3cWNHP-y-Bihkv-L98TdoiJS4DwYFv0eRp5124

###CREATE USER
POST {{apiUrl}}/createUser
Content-Type: application/json

{
    "name": "Erik",
    "password": "Erik",
    "user": "Erik",
    "boards": ["moro", "moro2", "Wallpapers"]
}

###LOGIN
POST {{apiUrl}}/login
Content-Type: application/json

{
    "password": "Erik",
    "user": "Erik"
}

###PATCH
PATCH {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "boards": ["default"]
}
