@apiUrl = http://localhost:3000/notes
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTFiZWU0YmI3YTU1NDU5ODVmNTFhZmEiLCJuYW1lIjoiRXJpayIsImV4cGlyZXNJbiI6IjFkIiwiYm9hcmRzIjpbIm1vcm8iLCJtb3JvMiIsIldhbGxwYXBlcnMiLCJtb3JvIiwibW9ybzMiLCJ3YWxscGFwZXJzIiwibW9ybzQ0IiwiZGVmYXVsdCJdLCJpYXQiOjE2OTYzNTY5NDR9.ByYYl8L6f1ppQ70RjTF6Ig27awmV7L9RwVTrRLdEdvA

###CREATE
POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "content": "Moro erik 3.10",
    "board": "moro",
    "heading": "Bigheading",
    "color": "red",
    "position": "1"
}

###READ
GET {{apiUrl}}/651c42a9a162e59bf7500f75
Content-Type: application/json
Authorization: Bearer {{token}}


###READALL
GET {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

###READ ALL NOTES FROM BOARD
GET {{apiUrl}}/board/default
Content-Type: application/json
Authorization: Bearer {{token}}

###UPDATE
PATCH {{apiUrl}}/651ad6c3e9d788c43711a58d
Content-Type: application/json
Authorization: Bearer {{token}}


{

    "content": "Googo gaagaa gogo"
}

###DELETE
DELETE {{apiUrl}}/651ad05e8977cfb0dff301c7
Content-Type: application/json
Authorization: Bearer {{token}}




