@apiUrl = http://localhost:3070/notes
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTI3YTk4MTEwNjBhZjVlMDQwNGIyMjIiLCJuYW1lIjoiVG9waSIsInVzZXIiOiJUb3BpIiwiZXhwaXJlc0luIjoiMWQiLCJpYXQiOjE2OTcxMjM0ODR9.6Ju9DZzmyacgzOHVIzb2sqCbO0oFZqLAnwU8lRf4y7Y


###CREATE new note in board
POST {{apiUrl}}/6527aa2517ad8e8e91dd416a
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "content": "Moro erik 12.10",
    "heading": "Bigheading",
    "color": "red",
    "position": "1"
}

###READ /noteId
GET {{apiUrl}}/65258098eed08f1ab50b6958
Content-Type: application/json
Authorization: Bearer {{token}}



###READ ALL NOTES FROM BOARD
GET {{apiUrl}}/board/65280ecbe130869d1dbb29ea
Content-Type: application/json
Authorization: Bearer {{token}}

###UPDATE /noteId
PATCH {{apiUrl}}/65258087eed08f1ab50b6956
Content-Type: application/json
Authorization: Bearer {{token}}


{

    "content": "Googo gaagaa gogo"
}

###DELETE /noteId
DELETE {{apiUrl}}/65258068e8c696183e623ea9
Content-Type: application/json
Authorization: Bearer {{token}}




