apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-app
  template:
    metadata:
      labels:
        app: socket-app
    spec:
      containers:
        - name: socket-container
          image: erikstob/wom-socketio:latest
          ports:
            - containerPort: 2000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: socket-jwt
                  key: jwt

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      initContainers:
        - name: wait-for-api-and-socket
          image: busybox
          command: ["/bin/sh", "-c", "until nc -z api-service 3070 && nc -z socketio-service 2000; do echo 'Waiting for API and Socket'; sleep 2; done;"]
      containers:
        - name: frontend-container
          image: erikstob/wom-frontend:latest
          ports:
            - containerPort: 3000
                    env:
            - name: SOCKET_URL
              value: "http://socketio-service.svc.cluster.local:2000"
              name: API_URL
              value: "http://api-service.svc.cluster.local:3070"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: api-container
          image: erikstob/wom-api:latest
          ports:
            - containerPort: 3070
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt
              name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb-url
                  key: url

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 3000 # Port on the service
      targetPort: 3000 # Port on the pod
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-app
  ports:
    - protocol: TCP
      port: 3070 # Port on the service
      targetPort: 3070 # Port on the pod
  type: NodePort 

---
apiVersion: v1
kind: Service
metadata:
  name: socketio-service
spec:
  selector:
    app: socketio-app
  ports:
    - protocol: TCP
      port: 2000 # Port on the service
      targetPort: 2000 # Port on the pod
  type: NodePort 
