apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-app
  template:
    metadata:
      labels:
        app: socket-app
    spec:
      containers:
        - name: socket-container
          image: erikstob/wom-socketio:latest
          ports:
            - containerPort: 2000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: socket-jwt
                  key: jwt

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-container
          image: erikstob/wom-frontend:latest
          ports:
            - containerPort: 3000


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: api-container
          image: erikstob/wom-api:latest
          ports:
            - containerPort: 3070
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt
              name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb-url
                  key: url

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 80 # Port on the service
      targetPort: 3000 # Port on the pod
  type: NodePort # Expose as a NodePort
