apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-frontend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-frontend
  template:
    metadata:
      labels:
        app: node-frontend
    spec:
      containers:
        - name: node-frontend-container
          image: docker.io/library/frontend:latest # Replace with your Docker image and tag
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api-container
          image: docker.io/library/api:latest # Replace with your Docker image and tag
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: node-frontend-service
  namespace: default
spec:
  selector:
    app: node-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer # Depending on your setup, you may choose a different service type
