apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-app
  template:
    metadata:
      labels:
        app: socket-app
    spec:
      containers:
        - name: socket-container
          image: erikstob/wom-socketio:latest
          ports:
            - containerPort: 2000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-container
          image: erikstob/wom-frontend:latest
          ports:
            - containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: api-container
          image: erikstob/wom-api:latest
          ports:
            - containerPort: 3070

---
apiVersion: v1
kind: Service
metadata:
  name: node-frontend-service
spec:
  selector:
    app: your-node-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 # Assuming your Node.js app is listening on port 3000
  type: NodePort
